# Generated by Django 5.2.1 on 2025-08-27 17:02

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_alter_restaurantprofile_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Логотип ресторана для отображения в меню",
                max_length=255,
                null=True,
                storage=core.utils.UniqueFilenameStorage(),
                upload_to="restaurants/logos/",
                verbose_name="Логотип",
            ),
        ),
    ]
