# Generated by Django 5.2.1 on 2025-08-28 11:32

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_alter_restaurantprofile_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantprofile",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="Сгенерированный QR-код для меню",
                max_length=255,
                null=True,
                storage=core.utils.UniqueFilenameStorage(),
                upload_to="restaurants/qr_codes/",
                verbose_name="QR-код",
            ),
        ),
    ]
