# Generated by Django 5.2.1 on 2025-08-27 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "restaurant_name",
                    models.CharField(
                        help_text="Полное название вашего ресторана",
                        max_length=200,
                        verbose_name="Название ресторана",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Полный адрес ресторана с указанием города, улицы, номера здания",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Номер телефона для связи с администрацией",
                        max_length=17,
                        verbose_name="Контактный телефон",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email для связи (если отличается от основного)",
                        max_length=254,
                        verbose_name="Контактный email",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание концепции, кухни, особенностей",
                        verbose_name="Описание ресторана",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True,
                        help_text="Загрузите документ, подтверждающий право на ведение деятельности (ИНН, свидетельство и т.д.)",
                        null=True,
                        upload_to="verification/documents/",
                        verbose_name="Документ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает рассмотрения"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                            ("requires_changes", "Требует изменений"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True,
                        help_text="Комментарий администратора при рассмотрении заявки",
                        verbose_name="Комментарий администратора",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата подачи заявки"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата рассмотрения"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_verification",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на верификацию ресторана",
                "verbose_name_plural": "Заявки на верификацию ресторанов",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
