# Generated by Django 5.2.1 on 2025-08-27 17:02

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verification", "0002_alter_restaurantverification_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantverification",
            name="document_file",
            field=models.FileField(
                blank=True,
                help_text="Загрузите документ, подтверждающий право на ведение деятельности (ИНН, свидетельство и т.д.)",
                max_length=255,
                null=True,
                storage=core.utils.UniqueFilenameStorage(),
                upload_to="verification/documents/",
                verbose_name="Документ",
            ),
        ),
    ]
