# Generated by Django 5.2.1 on 2025-08-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_restaurant_owner",
            field=models.BooleanField(
                default=False,
                help_text="Пользователь может регистрировать рестораны",
                verbose_name="Владелец ресторана",
            ),
        ),
    ]
