# Generated by Django 5.2.1 on 2025-08-28 11:32

import core.utils
import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Изображение категории (необязательно)",
                max_length=255,
                null=True,
                storage=core.utils.UniqueFilenameStorage(),
                upload_to=menu.models.category_image_upload_path,
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Фото блюда",
                max_length=255,
                null=True,
                storage=core.utils.UniqueFilenameStorage(),
                upload_to=menu.models.dish_image_upload_path,
                verbose_name="Изображение",
            ),
        ),
    ]
