# Generated by Django 5.2.1 on 2025-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_alter_category_image_alter_dish_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="weight_unit",
            field=models.CharField(
                choices=[
                    ("g", "г (граммы)"),
                    ("kg", "кг (килограммы)"),
                    ("ml", "мл (миллилитры)"),
                    ("l", "л (литры)"),
                    ("pcs", "шт (штуки)"),
                ],
                default="g",
                help_text="Единица измерения веса/объема",
                max_length=5,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="weight",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Вес или объем порции",
                null=True,
                verbose_name="Вес/Объем",
            ),
        ),
    ]
